FROM alpine:latest AS builder

RUN apk add --no-cache curl \
	&& while [ "$S6_DOWNLOAD_URL" == "" ] ; do S6_DOWNLOAD_URL=$(curl -s https://api.github.com/repos/just-containers/s6-overlay/releases/latest | grep "browser_download_url" | grep "s6-overlay-armhf.tar.gz\"" | cut -d\" -f4) ; done \
	&& curl --retry 3 -L -s -o /tmp/s6-overlay-armhf.tar.gz $S6_DOWNLOAD_URL \
	&& mkdir /tmp/s6-overlay \
	&& tar xzf /tmp/s6-overlay-armhf.tar.gz -C /tmp/s6-overlay \
#	&& while [ "$QEMU_DOWNLOAD_URL" == "" ] ; do QEMU_DOWNLOAD_URL=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/releases/latest | grep "browser_download_url" | grep "\/qemu-arm-static.tar.gz" | cut -d\" -f4) ; done \
	&& QEMU_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-3/qemu-arm-static.tar.gz" \
	&& curl --retry 3 -L -s -o /tmp/qemu-arm-static.tar.gz $QEMU_DOWNLOAD_URL \
	&& tar xzf /tmp/qemu-arm-static.tar.gz -C /tmp

FROM arm32v6/alpine:latest

COPY --from=builder /tmp/s6-overlay /
COPY --from=builder /tmp/qemu-arm-static /usr/bin 

ENTRYPOINT ["/init"]
