FROM alpine:edge AS builder

RUN apk add --no-cache curl \
	&& S6_DOWNLOAD_URL=$(curl -s https://api.github.com/repos/just-containers/s6-overlay/releases/latest | grep "browser_download_url" | grep "s6-overlay-armhf.tar.gz\"" | cut -d\" -f4) \
	&& curl -L -s -o /tmp/s6-overlay-armhf.tar.gz $S6_DOWNLOAD_URL \
	&& mkdir /tmp/s6-overlay \
	&& tar xzf /tmp/s6-overlay-armhf.tar.gz -C /tmp/s6-overlay \
	&& QEMU_DOWNLOAD_URL=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/releases/latest | grep "browser_download_url" | grep "\/qemu-arm-static.tar.gz" | cut -d\" -f4) \
	&& curl -L -s -o /tmp/qemu-arm-static.tar.gz $QEMU_DOWNLOAD_URL \
	&& tar xzf /tmp/qemu-arm-static.tar.gz -C /tmp

FROM arm32v6/alpine:edge

COPY --from=builder /tmp/s6-overlay /
COPY --from=builder /tmp/qemu-arm-static /usr/bin 

RUN sed -i "s/v3.7/edge/g" /etc/apk/repositories \
	&& apk upgrade --no-cache

ENTRYPOINT ["/init"]
