all: build push

edit:
	docker run --rm -it -v piwigo-souvenirs_config:/config -v piwigo_config:/piwigo -v ${PWD}/piwigo-souvenirs.go:/go/main.go --network docker_default golang:alpine /bin/sh

build:
	docker build -t napnap75/rpi-piwigo-souvenirs .

login:
	if [ "${DOCKER_USERNAME}" != "" ]; then docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" ; fi

push: login
	docker push napnap75/rpi-piwigo-souvenirs
