@@ -18,7 +18,8 @@
 RUN if [ -n "${GITEA_VERSION}" ]; then git checkout "${GITEA_VERSION}"; fi \
-  && make clean generate build
+  && env EXTRA_GOFLAGS="GOARM=6 GOARCH=arm" make clean generate build

-FROM alpine:3.7
+FROM arm32v6/alpine:3.7
+COPY qemu-arm-static /usr/bin/qemu-arm-static
 LABEL maintainer="maintainers@gitea.io"

 EXPOSE 22 3000
 
