@@ -1,7 +1,8 @@

 ###################################
 #Build stage
-FROM golang:1.10-alpine3.7 AS build-env
+FROM arm32v6/golang:1.10-alpine3.7 AS build-env
+COPY qemu-arm-static /usr/bin/qemu-arm-static

 ARG GITEA_VERSION
 ARG TAGS="sqlite"
@@ -18,7 +19,8 @@
 RUN if [ -n "${GITEA_VERSION}" ]; then git checkout "${GITEA_VERSION}"; fi \
  && make clean generate build

-FROM alpine:3.7
+FROM arm32v6/alpine:3.7
+COPY qemu-arm-static /usr/bin/qemu-arm-static
 LABEL maintainer="maintainers@gitea.io"

 EXPOSE 22 3000
 
