FROM alpine:3.7 AS builder

ADD https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz /tmp
RUN tar xzf /tmp/qemu-arm-static.tar.gz -C /tmp

FROM arm32v7/nextcloud:%VERSION%-%VARIANT%

COPY --from=builder /tmp/qemu-arm-static /usr/bin 

RUN apt-get update && apt-get install -y smbclient && rm -rf /var/lib/apt/lists/*
