FROM arm32v6/alpine:3.6

COPY qemu-arm-static /usr/bin/qemu-arm-static

ADD https://dl.minio.io/client/mc/release/linux-arm/mc /usr/bin/

RUN apk add --no-cache ca-certificates && \
	chmod +x /usr/bin/mc

ENTRYPOINT ["mc"]
